# Generated by Django 5.0.1 on 2024-01-13 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graph.node')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('graph.node',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graph.node')),
                ('name_last', models.CharField(max_length=200)),
                ('name_first', models.CharField(max_length=200)),
            ],
            bases=('graph.node',),
        ),
    ]
