# Generated by Django 5.0.1 on 2024-01-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('child_of', 'child of'), ('has_child', 'has child'), ('spouse_of', 'spouse of'), ('sibling_of', 'sibling of'), ('friend_of', 'friend of')], max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('reciprocal_edge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.edge')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graph.node')),
                ('kind', models.CharField(blank=True, choices=[(None, 'not specified'), ('performance', 'performance'), ('gathering', 'gathering')], max_length=20)),
            ],
            bases=('graph.node',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graph.node')),
                ('gender', models.CharField(blank=True, choices=[(None, 'not specified'), ('female', 'female'), ('male', 'male'), ('nonbinary', 'non-binary')], max_length=20)),
            ],
            bases=('graph.node',),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graph.node')),
                ('kind', models.CharField(blank=True, choices=[(None, 'not specified'), ('dwelling', 'dwelling'), ('business', 'business')], max_length=20)),
            ],
            bases=('graph.node',),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graph.node')),
                ('kind', models.CharField(blank=True, choices=[(None, 'not specified'), ('org', 'organization'), ('collection', 'object collection'), ('series', 'event series'), ('bibliography', 'list of works')], max_length=20)),
            ],
            bases=('graph.node',),
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graph.node')),
                ('is_work', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, choices=[(None, 'not specified'), ('object', 'object'), ('article', 'article'), ('artwork', 'artwork'), ('book', 'book'), ('sculpture', 'sculpture'), ('website', 'website')], max_length=20)),
            ],
            bases=('graph.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='nodes',
            field=models.ManyToManyField(through='graph.Edge', to='graph.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='dobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='graph.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dobjects', to='graph.node'),
        ),
    ]
