# Generated by Django 5.0.1 on 2024-01-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parent_of', 'parent of'), ('has_parent', 'has parent')], max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('node_dobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_node', to='graph.node')),
                ('node_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_node', to='graph.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='nodes',
            field=models.ManyToManyField(through='graph.NodeRelation', to='graph.node'),
        ),
    ]
