# Generated by Django 5.0.1 on 2024-01-21 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='reciprocal_edge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.edge'),
        ),
    ]
