# Generated by Django 5.0.1 on 2024-01-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parent_of', 'parent of'), ('spouse_of', 'spouse_of')], max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('dobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='graph.node')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dobjects', to='graph.node')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='nodes',
            field=models.ManyToManyField(through='graph.Edge', to='graph.node'),
        ),
        migrations.DeleteModel(
            name='NodeRelation',
        ),
    ]
