# Generated by Django 5.0.1 on 2024-01-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_person_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
